apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vendor-app-ingress
  namespace: vendor-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: management.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: management-service
                port:
                  number: 80
    - host: events.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: event-service
                port:
                  number: 80
